mod 'elastic-kibana', '6.3.1'
mod 'elastic-elastic_stack', '7.0.0'
mod 'puppetlabs-stdlib', '6.1.0'
mod 'puppetlabs-apt', '7.1.0'
mod 'puppetlabs-translate', '2.0.0'
mod 'puppet-yum', '4.0.0'
mod 'puppetlabs-concat', '6.1.0'
mod 'puppetlabs-yumrepo_core', '1.0.3'